// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts/access/AccessControl.sol";

/**
 * @title CricketVault - ICC Champions Trophy Anti-Scalping System
 * @notice Mints NFT tickets and stores booking references off-chain via IPFS.
 */
contract CricketVault is ERC721URIStorage, AccessControl {
    
    bytes32 public constant ORGANIZER_ROLE = keccak256("ORGANIZER_ROLE");
    uint256 public nextTicketId;

    struct TicketRecord {
        string ticketId;
        string ipfsHash;
        uint256 price;
        address buyer;
        uint256 timestamp;
    }
    
    // Mapping from tokenId to its full booking record
    mapping(uint256 => TicketRecord) public ticketBookings;

    // Events for tracking and frontend integration
    event Deposit(string indexed ticketId, address indexed user, uint256 amount);
    event TicketMinted(uint256 indexed tokenId, string ticketId, string ipfsHash);

    constructor() ERC721("ICC Champions Trophy", "ICC") {
        _grantRole(DEFAULT_ADMIN_ROLE, msg.sender);
        _grantRole(ORGANIZER_ROLE, msg.sender);
    }

    /**
     * @notice Mints a new ticket NFT.
     * @param _ticketId The unique ID generated by your backend/crypto.randomBytes.
     * @param _ipfsHash The CID returned from Pinata.
     */
    function buyTicket(string memory _ticketId, string memory _ipfsHash) public payable {
        require(msg.value > 0, "Ticket price must be greater than 0");

        uint256 tokenId = nextTicketId;
        nextTicketId++;

        // Store the detailed record in the struct
        ticketBookings[tokenId] = TicketRecord({
            ticketId: _ticketId,
            ipfsHash: _ipfsHash,
            price: msg.value,
            buyer: msg.sender,
            timestamp: block.timestamp
        });

        // 1. Mint the NFT
        _safeMint(msg.sender, tokenId);

        // 2. Set the Metadata URI (Industry standard for wallets to find your Pinata JSON)
        string memory tokenURI = string(abi.encodePacked("ipfs://", _ipfsHash));
        _setTokenURI(tokenId, tokenURI);

        // Emit events for Hardhat and React
        emit Deposit(_ticketId, msg.sender, msg.value);
        emit TicketMinted(tokenId, _ticketId, _ipfsHash);
    }

    /**
     * @notice Fetch the original price paid for a ticket (useful for anti-scalping logic)
     */
    function getOriginalPrice(uint256 _tokenId) public view returns (uint256) {
        return ticketBookings[_tokenId].price;
    }

    /**
     * @notice Returns the full record for a ticket
     */
    function getTicketDetails(uint256 _tokenId) public view returns (TicketRecord memory) {
        return ticketBookings[_tokenId];
    }

    // Required overrides for Solidity inheritance
    function supportsInterface(bytes4 interfaceId) public view override(ERC721URIStorage, AccessControl) returns (bool) {
        return super.supportsInterface(interfaceId);
    }

    /**
     * @notice Withdraw funds to the Organizer's wallet
     */
    function withdraw() public onlyRole(ORGANIZER_ROLE) {
        uint256 balance = address(this).balance;
        require(balance > 0, "No funds to withdraw");
        payable(msg.sender).transfer(balance);
    }
}